config:
  # If a property in the configuration is deprecated, that'll fail Detekt execution.
  warningsAsErrors: true

processors:
  # Blanket disable processors as they are not used.
  # Stats would show up in HTML report, but since that's not mergeable it has little value per module.
  active: false


console-reports:
  exclude:
    # Disabled because I don't want to see what kind of reports are generate every time I run detekt.
    - 'NotificationReport'
    # Enabled, because it gives the category of the rules.
    #- 'IssuesReport'
    # Disabled, because it's very verbose, even more so than IssuesReport.
    - 'FileBasedIssuesReport'
    # Disabled, because this gives enough context to see the problems, but doesn't group rules.
    - 'LiteIssuesReport'


comments:

  DocumentationOverPrivateFunction:
    # Disabled as I don't agree with it, if a function needs docs, it needs docs. Visibility doesn't change that.
    active: false

  DocumentationOverPrivateProperty:
    # Disabled as I don't agree with it, if a function needs docs, it needs docs. Visibility doesn't change that.
    active: false

  OutdatedDocumentation:
    allowParamOnConstructorProperties: true

  UndocumentedPublicClass:
    # Disabled as this is not a public library. For now it's not even all in Kotlin.
    active: false
    # Enforce for production and test code. This negates the excludes in default config.
    excludes: [ ]

  UndocumentedPublicFunction:
    # Disabled as this is not a public library. For now it's not even all in Kotlin.
    active: false
    # Enforce for production and test code. This negates the excludes in default config.
    excludes: [ ]

  UndocumentedPublicProperty:
    # Disabled as this is not a public library. For now it's not even all in Kotlin.
    active: false
    # Enforce for production and test code. This negates the excludes in default config.
    excludes: [ ]


complexity:

  NamedArguments:
    # Exclude in test code, mocking doesn't need to have explicit named arguments, since a minor mistake will fail the tests.
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  StringLiteralDuplication:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  TooManyFunctions:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]


exceptions:

  InstanceOfCheckForException:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  ThrowingExceptionsWithoutMessageOrCause:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  TooGenericExceptionCaught:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]


naming:

  BooleanPropertyNaming:
    allowedPattern: ^(is|has|are|show|use)

  ConstructorParameterNaming:
    excludes:
      - '**/endpoint/*/data/*.kt'
      - '**/quickbook/Quickbook*.kt'

  FunctionNaming:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  FunctionNameMaxLength:
    ignoreAnnotated:
      # Test names in JUnit 4 are ok to be long as they're likely sentences.
      - 'org.junit.Test'
      # Test names in JUnit 5 are ok to be long as they're likely sentences.
      - 'org.junit.jupiter.api.Test'
      - 'org.junit.jupiter.api.TestFactory'
      - 'org.junit.jupiter.api.TestTemplate'
      - 'org.junit.jupiter.api.RepeatedTest'
      - 'org.junit.jupiter.params.ParameterizedTest'
      - 'org.junitpioneer.jupiter.RetryingTest'
      - 'org.junitpioneer.jupiter.cartesian.CartesianTest'

  VariableNaming:
    excludes:
      - '**/database/model/*.kt'


performance:

  SpreadOperator:
    active: false


potential-bugs:

  ImplicitUnitReturnType:
    ignoreAnnotated:
      # Convention in unit tests might be to do runBlockingTest {} or endpointTest {}.
      - 'org.junit.jupiter.api.Test'

  LateinitUsage:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]
    ignoreAnnotated:
      - 'org.neo4j.ogm.annotation.Property'
      - 'org.neo4j.ogm.annotation.Relationship'
      - 'com.fasterxml.jackson.annotation.JsonManagedReference'

  MissingPackageDeclaration:
    # It's often desirable to declare functions and classes on the default package,
    # so that it can be used unqualified from gradle.build.kts files.
    excludes:
      - '**/gradle/plugins/src/main/kotlin/**'
      - '**/build.gradle.kts'
      - '**/settings.gradle.kts'
  
  UnnamedParameterUse:
    ignoreFunctionCall:
      - 'io.ktor.client.request.header'
      - 'io.ktor.client.request.parameter'
      - 'io.ktor.server.response.header'
      - 'kotlin.collections.associateBy'
      - 'kotlin.text.replace'
      - 'kotlin.text.substring'
      - 'net.twisterrob.cinema.cineworld.backend.ktor.putIfAbsent'
      - 'net.twisterrob.test.that'

  UnsafeCallOnNullableType:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]


style:

  ForbiddenComment:
    comments:
      - 'FIXME'
      - 'STOPSHIP'

  NoTabs:
    # I'm a tab guy, I don't pay for space in advance.
    active: false

  MagicNumber:
    excludes: [ '**/unitTest/**', '**/functionalTest/**', '**/integrationTest/**', '**/integrationExternalTest/**' ]

  MaxLineLength:
    # It's unavoidable to have some long lines when stacktraces or links are added as comments.
    excludeCommentStatements: true

  MultilineRawStringIndentation:
    # Account for tabs.
    indentSize: 1

  UnusedPrivateClass:
    excludes:
      - '**/*Test.kt'

  VarCouldBeVal:
    ignoreLateinitVar: true
