name: "ðŸ”¨ Build & Check (Gradle) - stand-in"
on:
  workflow_call

jobs:

  check:
    name: "ðŸ”¨ Gradle"

    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Publish 'detekt' GitHub Code Scanning analysis."
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: '.github/workflows/Heroku-check-gradle.yml:check'
          sarif_file: ${{ github.workspace }}/.github/workflows/empty-reports/detekt.sarif

      - name: "Publish 'ðŸ”” Test Results' check run."
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: 'ðŸ”” Test Results'
          comment_mode: off
          ignore_runs: true
          job_summary: false
          compare_to_earlier_commit: false
          check_run_annotations: false
          fail_on: nothing
          test_changes_limit: 0
          junit_files: ${{ github.workspace }}/.github/workflows/empty-reports/junit.xml
