name: "ğŸ” Static Checks (Map) - stand-in"
on:
  workflow_call

jobs:
  detekt:
    name: "ğŸ” Static Checks (Map)"

    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Publish 'detekt' GitHub Code Scanning analysis."
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: '.github/workflows/map-detekt.yml:detekt'
          sarif_file: ${{ github.workspace }}/.github/workflows/empty-reports/detekt.sarif
